# This rule is not used by the project ai-gateway-litellm itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over gateway.agentic-layer.ai.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ai-gateway-litellm
    app.kubernetes.io/managed-by: kustomize
  name: modelrouter-admin-role
rules:
- apiGroups:
  - gateway.agentic-layer.ai
  resources:
  - modelrouters
  verbs:
  - '*'
- apiGroups:
  - gateway.agentic-layer.ai
  resources:
  - modelrouters/status
  verbs:
  - get
