---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runtime.agentic-layer.ai
  resources:
  - aigatewayclasses
  - guardrailproviders
  - guards
  - toolgatewayclasses
  - toolroutes
  - toolservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - runtime.agentic-layer.ai
  resources:
  - aigateways
  - toolgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runtime.agentic-layer.ai
  resources:
  - aigateways/finalizers
  - toolgateways/finalizers
  verbs:
  - update
- apiGroups:
  - runtime.agentic-layer.ai
  resources:
  - aigateways/status
  - toolgateways/status
  - toolroutes/status
  verbs:
  - get
  - patch
  - update
