apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use default configuration as base
resources:
- ../default

# Patch for local development
patches:
- path: manager_local_patch.yaml
  target:
    kind: Deployment
    name: controller-manager
    namespace: system